### ISSUE TITLE
`ocamlbuild` fails due to leftover compiled files

### ISSUE THREAD

**Issue by zhengqunkoo** [hipsleek/hipsleek#17]
## Steps to Reproduce
Travis job log:
1. First, all dependencies are installed, and `make` is invoked:
   ```
   make
   ```
   which by default, processes the first rule, in this case, `all`.
1. Then, `make` traverses through the rules, and the `xml` rule is processed fine.
   ```
   cd /home/travis/build/zhengqunkoo/hipsleek/xml; make all; make opt; cd ..
   ocamlopt -o xml-light.cmxa -a  xml_parser.cmx xml_lexer.cmx dtd.cmx xmlParser.cmx xml.cmx
   ocamlopt xml-light.cmxa test.ml -o test_opt.exe
   make[1]: Leaving directory `/home/travis/build/zhengqunkoo/hipsleek/xml'
   make[1]: Entering directory `/home/travis/build/zhengqunkoo/hipsleek/xml'
   make[1]: Nothing to be done for `opt'.
   make[1]: Leaving directory `/home/travis/build/zhengqunkoo/hipsleek/xml'
   ```
1. So, the `sleek.byte` rule is processed. But `ocamlbuild` fails:
   ```
   IMPORTANT: I cannot work with leftover compiled files.
   ```
   also known as files with suffix `.so`, `.a`, and `.o`.
## Expected Behavior
Build does not fail.
## Actual Behavior
`ocamlbuild` fails purely due to all leftover compiled files from [hipsleek/dependencies](https://github.com/hipsleek/dependencies).

**Comment by zhengqunkoo** [comment]
Some unsatisfactory solutions are to:
1. Not clone the [hipsleek/dependencies](https://github.com/hipsleek/dependencies) submodule
1. Clone the [hipsleek/dependencies](https://github.com/hipsleek/dependencies) submodule, but move it to outside of this repository

**Comment by benedictleejh** [comment]
If the dependencies are cloned into a `dependencies` directory, it's failing because `ocamlbuild` does not ignore that directory when doing its hygiene checks. A quick solution then would be to add that directory to be ignored in the `_tags` file. Following the syntax used for other directories (e.g. `xml`) we ignore should be fine.

**Comment by zhengqunkoo** [comment]
With modified `_tags`, now `ocamlbuild` and probably `make` run fine. But `rake` modifies `_tags`, so the tag should be added to `Rakefile` instead.

**Comment by zhengqunkoo** [comment]
Tag should still be in `_tags`.
