### ISSUE TITLE
cannot run fixcalc on mac m2 chip

### ISSUE THREAD

**Issue by Sdywolf** [hipsleek/hipsleek#55]
Hello, I'm really interested in SLEEK and want to try it on my mac m2 machine. But when I follow the instructions to build SLEEK, I found that the **fixcalc** binary provided in ./dependencies doesn't run on my machine. The result when I run "../../sleek --inv --dis-eps sleek/infer/app-inv.slk" in ./example/working is below:

```
ERROR : fixcalc cannot be found!!

!!! **src/tpdispatcher.ml#492:init_tp by default:
!!! **src/tpdispatcher.ml#391:set_tp z3Starting z3...

!!! **WARNING****src/sleek.ml#494:[../../prelude.slk,sleek/infer/app-inv.slk]/bin/sh: fixcalc: command not found

Exception processed: Failure("nth")
error at:
SLEEK FAILURE (END)

Stop z3... 0 invocations
0 false contexts at: ()

!!! log(small):(0.,0)
Total verification time: 0.079092 second(s)
	Time spent in main process: 0.071907 second(s)
	Time spent in child processes: 0.007185 second(s)
```

I tried to build **fixcalc** from source, but cannot find code of **fixcalc** online. Could you help me?

**Comment by dariusf** [comment]
I have added instructions for building fixcalc from source to the readme. Do give them a try.

**Comment by Sdywolf** [comment]
Thanks! Your instructions help me take a big step forward! But I still have a problem when building omega_stub. I follow the guidance to build Omega and Mona. Then, I try to build Fixcalc. When I try to make in directory omega_stub, there's an error occurred:
```
cd src && make all
make[1]: Entering directory '/Users/Sdywolf/Documents/Projects/omega_stub/src'
g++ -DOMIT_QUANTIFY_CALLS -g -Wall -DSIG_HANDLER_HAS_ONE_ARG=1 -DSHUT_UP_ABOUT_STATEMENT_WITH_NO_EFFECT_IN_DYNAMIC_ARRAY_CREATION -Wno-deprecated -I/Users/darius/hipsleek/omega_modified/omega_lib/include -I/Users/darius/hipsleek/omega_modified/code_gen/include -I/Users/darius/hipsleek/omega_modified/basic/include -I. -c omega_stub.cpp -o ../lib/../lib/omega_stub.o
omega_stub.cpp:5:10: fatal error: 'omega.h' file not found
#include <omega.h>
         ^~~~~~~~~
1 error generated.
make[1]: *** [Makefile:19: ../lib/omega_stub.o] Error 1
make[1]: Leaving directory '/Users/Sdywolf/Documents/Projects/omega_stub/src'
make: *** [Makefile:9: lib] Error 2
``` 
It seems that the omega.h is missing. I wonder if it was because the organization of my files, the file tree of my directory is as below:
```
.
├── fixcalc
├── hipsleek
├── omega_stub
```

**Comment by dariusf** [comment]
Right, I updated both subprojects too. hipsleek/omega_stub@f352530fff573faa4fd80ddd60a6f9ece3459330 in particular removes hardcoded paths.

Could you pull the latest changes for both, and also make them subdirectories of hipsleek?

```
hipsleek
├── fixcalc_src
└── omega_stub
```

The scripts in the readme should then all be run from the hipsleek directory.

**Comment by Sdywolf** [comment]
Thanks! Now sleek can work without complaining on my machine! Also, I've noticed that the Makefile.rules in omega_stub and the Makefile in fixcalc contain some absolute path that contains "darius". Maybe it should be replaced by relative path.

**Comment by dariusf** [comment]
Thank you, I've removed them.
